### 고객 회원정보 수정
PUT http://localhost:8080/manage/customer/update
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJNM0lYSW5MaDZwTG1YU2t4WFNGczNlUE1KbDFHSUNBYllOdlFlVUtzMGJZPSIsImp0aSI6IkNtWUR2NU1LNVlVeWlrOEtHTkR3b3c9PSIsInJvbGVzIjoiT1dORVIiLCJpYXQiOjE3NDEzMTIyNTcsImV4cCI6MTc0MTM5ODY1N30.eVRc7qG3UTRz_0tozUPQyKkoy7IzL3pfBmEaJ-3B4SY

{
  "phone": "010-5000-2223",
  "name": "mike2",
  "account": "1111-1111-1111-1111"
}

###점주 회원정보 수정
PUT http://localhost:8080/manage/owner/update
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJNM0lYSW5MaDZwTG1YU2t4WFNGczNlUE1KbDFHSUNBYllOdlFlVUtzMGJZPSIsImp0aSI6IkNtWUR2NU1LNVlVeWlrOEtHTkR3b3c9PSIsInJvbGVzIjoiT1dORVIiLCJpYXQiOjE3NDEzMTIyNTcsImV4cCI6MTc0MTM5ODY1N30.eVRc7qG3UTRz_0tozUPQyKkoy7IzL3pfBmEaJ-3B4SY

{
"phone": "010-5000-2223",
"name": "mike2",
"account": "1111-1111-1111-1111"
}

